version: "3.8"

services:

  app:
    container_name: app
    build: ./app/.
    networks:
      - node-network
    tty: true
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    env_file:
      ./.env 
    ports:
      - "3306:3306"
    volumes: 
       - ./mysql:/var/lib/mysql
       - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql       
    networks:
      - node-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    env_file:
      ./.env 
    restart: always
    ports:
      - 8085:80
    networks:
      - node-network
networks:
  node-network:
    driver: bridge